env:
  global:
    - CI_NAME=travis-pro
    - COVERALLS_REPO_TOKEN=Mu29ps8sSR7qM0gE991CspgQ6AhsstmOS

language: java
jdk:
  - oraclejdk8          // tells Travis to use Java 8

after_success:
  - gradle jacocoTestReport coveralls
